In [1]:
import pandas as pd
df = pd.read_csv("Hostel_Management_Dataset_Filled.csv")
print(df.head())
print(df.dtypes)

  Resident_ID Resident_Name  Gender Date_of_Birth  Mobile_Number  \
0      R00001    Resident 1    Male    1991-02-02      800000001
1      R00002    Resident 2  Female    1992-03-03      800000002
2      R00003    Resident 3    Male    1993-04-04      800000003
3      R00004    Resident 4  Female    1994-05-05      800000004
4      R00005    Resident 5    Male    1995-06-06      800000005

                   Email  Aadhaar_Number Company_Name Employee_ID  \
0  resident1@example.com    100000000001      Infosys    EMP00001
1  resident2@example.com    100000000002        Wipro    EMP00002
2  resident3@example.com    100000000003    Accenture    EMP00003
3  resident4@example.com    100000000004    Capgemini    EMP00004
4  resident5@example.com    100000000005          TCS    EMP00005

          Occupation  ... Religion  ID_Proof_Type Aadhaar_Copy Voter_ID_Copy  \
0            Analyst  ...    Hindu        Aadhaar          Yes           Yes
1             Tester  ...    Hindu        Aadhaar          Yes           Yes
2   Support Engineer  ...    Hindu        Aadhaar          Yes           Yes
3  Software Engineer  ...    Hindu        Aadhaar          Yes           Yes
4            Analyst  ...    Hindu        Aadhaar          Yes           Yes

  Joining_Date  Exit_Date  Bed_Status  Room_Capacity  Available_Beds  Remarks
0   2026-01-01        NaN    Occupied              2               0      NaN
1   2026-01-01        NaN    Occupied              2               0      NaN
2   2026-01-01        NaN    Occupied              2               0      NaN
3   2026-01-01        NaN    Occupied              2               1      NaN
4   2026-01-01        NaN    Occupied              2               0      NaN

[5 rows x 43 columns]
Resident_ID           object
Resident_Name         object
Gender                object
Date_of_Birth         object
Mobile_Number          int64
Email                 object
Aadhaar_Number         int64
Company_Name          object
Employee_ID           object
Occupation            object
Check_In_Date         object
Check_Out_Date       float64
Room_Number           object
Bed_Number            object
Room_Type             object
Floor                  int64
Monthly_Rent           int64
Deposit_Amount         int64
Amount_Paid            int64
Balance_Amount         int64
Payment_Date          object
Payment_Method        object
Payment_Status        object
Occupancy_Status      object
Resident_Status       object
Emergency_Contact      int64
Parent_Name           object
Parent_Contact         int64
Permanent_Address     object
City                  object
State                 object
Pincode                int64
Nationality           object
Religion              object
ID_Proof_Type         object
Aadhaar_Copy          object
Voter_ID_Copy         object
Joining_Date          object
Exit_Date            float64
Bed_Status            object
Room_Capacity          int64
Available_Beds         int64
Remarks              float64
dtype: object

In [2]:
date_columns = ["Date_of_Birth", "Check_In_Date", "Payment_Date", "Joining_Date"]
for col in date_columns:
    df[col] = pd.to_datetime(df[col], errors='coerce')
print(df[date_columns].dtypes)

Date_of_Birth    datetime64[ns]
Check_In_Date    datetime64[ns]
Payment_Date     datetime64[ns]
Joining_Date     datetime64[ns]
dtype: object

In [3]:
print(df.columns.tolist())

['Resident_ID', 'Resident_Name', 'Gender', 'Date_of_Birth', 'Mobile_Number', 'Email', 'Aadhaar_Number', 'Company_Name', 'Employee_ID', 'Occupation', 'Check_In_Date', 'Check_Out_Date', 'Room_Number', 'Bed_Number', 'Room_Type', 'Floor', 'Monthly_Rent', 'Deposit_Amount', 'Amount_Paid', 'Balance_Amount', 'Payment_Date', 'Payment_Method', 'Payment_Status', 'Occupancy_Status', 'Resident_Status', 'Emergency_Contact', 'Parent_Name', 'Parent_Contact', 'Permanent_Address', 'City', 'State', 'Pincode', 'Nationality', 'Religion', 'ID_Proof_Type', 'Aadhaar_Copy', 'Voter_ID_Copy', 'Joining_Date', 'Exit_Date', 'Bed_Status', 'Room_Capacity', 'Available_Beds', 'Remarks']

In [4]:
from datetime import datetime
today = pd.Timestamp.today()
df["Age"] = ((today - df["Date_of_Birth"]).dt.days // 365)
print(df[["Date_of_Birth", "Age"]].head())

  Date_of_Birth  Age
0    1991-02-02   35
1    1992-03-03   34
2    1993-04-04   33
3    1994-05-05   32
4    1995-06-06   31

In [5]:
invalid_age = df[(df["Age"] < 0) | (df["Age"] > 100)]
print("Invalid Age Records:", len(invalid_age))
invalid_age

Invalid Age Records: 0

Empty DataFrame
Columns: [Resident_ID, Resident_Name, Gender, Date_of_Birth, Mobile_Number, Email, Aadhaar_Number, Company_Name, Employee_ID, Occupation, Check_In_Date, Check_Out_Date, Room_Number, Bed_Number, Room_Type, Floor, Monthly_Rent, Deposit_Amount, Amount_Paid, Balance_Amount, Payment_Date, Payment_Method, Payment_Status, Occupancy_Status, Resident_Status, Emergency_Contact, Parent_Name, Parent_Contact, Permanent_Address, City, State, Pincode, Nationality, Religion, ID_Proof_Type, Aadhaar_Copy, Voter_ID_Copy, Joining_Date, Exit_Date, Bed_Status, Room_Capacity, Available_Beds, Remarks, Age]
Index: []

[0 rows x 44 columns]

In [6]:
invalid_deposit = df[df["Deposit_Amount"] < 0]
print("Invalid Deposit Amount Records:", len(invalid_deposit))
invalid_deposit

Invalid Deposit Amount Records: 0

Empty DataFrame
Columns: [Resident_ID, Resident_Name, Gender, Date_of_Birth, Mobile_Number, Email, Aadhaar_Number, Company_Name, Employee_ID, Occupation, Check_In_Date, Check_Out_Date, Room_Number, Bed_Number, Room_Type, Floor, Monthly_Rent, Deposit_Amount, Amount_Paid, Balance_Amount, Payment_Date, Payment_Method, Payment_Status, Occupancy_Status, Resident_Status, Emergency_Contact, Parent_Name, Parent_Contact, Permanent_Address, City, State, Pincode, Nationality, Religion, ID_Proof_Type, Aadhaar_Copy, Voter_ID_Copy, Joining_Date, Exit_Date, Bed_Status, Room_Capacity, Available_Beds, Remarks, Age]
Index: []

[0 rows x 44 columns]

In [7]:
invalid_paid = df[
    (df["Amount_Paid"] < 0) |
    (df["Amount_Paid"] > df["Deposit_Amount"])
]
print("Invalid Amount Paid Records:", len(invalid_paid))
invalid_paid

Invalid Amount Paid Records: 0

Empty DataFrame
Columns: [Resident_ID, Resident_Name, Gender, Date_of_Birth, Mobile_Number, Email, Aadhaar_Number, Company_Name, Employee_ID, Occupation, Check_In_Date, Check_Out_Date, Room_Number, Bed_Number, Room_Type, Floor, Monthly_Rent, Deposit_Amount, Amount_Paid, Balance_Amount, Payment_Date, Payment_Method, Payment_Status, Occupancy_Status, Resident_Status, Emergency_Contact, Parent_Name, Parent_Contact, Permanent_Address, City, State, Pincode, Nationality, Religion, ID_Proof_Type, Aadhaar_Copy, Voter_ID_Copy, Joining_Date, Exit_Date, Bed_Status, Room_Capacity, Available_Beds, Remarks, Age]
Index: []

[0 rows x 44 columns]

In [8]:
print("Gender:", df["Gender"].unique())
print("City:", df["City"].unique())
print("State:", df["State"].unique())

Gender: ['Male' 'Female']
City: ['Vijayawada' 'Hyderabad' 'Chennai' 'Guntur']
State: ['Andhra Pradesh' 'Telangana' 'Tamil Nadu']